#!/usr/bin/env Rscript
################################################################################
# generate-snap-wdl.R
#
# Generate wdl/snap.wdl with all downstream modules optional (Sprocket 0.30.x).
# Each module runs only when its run_* workflow input is true. Skipped modules
# do not block later modules; wait_on chains to the last completed step.
#
# Usage:
#   Rscript scripts/generate-snap-wdl.R [--output wdl/snap.wdl]
################################################################################

parse_args <- function(args) {
  out <- list(output = "wdl/snap.wdl")
  i <- 1L
  while (i <= length(args)) {
    if (args[[i]] == "--output") {
      i <- i + 1L
      out$output <- args[[i]]
    }
    i <- i + 1L
  }
  out
}

MODULES <- list(
  list(id = "upstream", task = "run_upstream", flag = "run_upstream",
       cpu = "upstream_cpu", memory = "upstream_memory_gb",
       future = "upstream_future_globals_gib", queue = "upstream_lsf_queue"),
  list(id = "integrative", task = "run_integrative", flag = "run_integrative",
       cpu = "integrative_cpu", memory = "integrative_memory_gb",
       future = "integrative_future_globals_gib", queue = "integrative_lsf_queue"),
  list(id = "cluster", task = "run_cluster", flag = "run_cluster",
       cpu = "cluster_cpu", memory = "cluster_memory_gb",
       future = "cluster_future_globals_gib", queue = "cluster_lsf_queue"),
  list(id = "contamination", task = "run_contamination_removal", flag = "run_contamination_removal",
       cpu = "contamination_cpu", memory = "contamination_memory_gb",
       future = "contamination_future_globals_gib", queue = "contamination_lsf_queue"),
  list(id = "cell_types", task = "run_cell_types", flag = "run_cell_types",
       cpu = "cell_types_cpu", memory = "cell_types_memory_gb",
       future = NA, queue = "cell_types_lsf_queue"),
  list(id = "clone_phylogeny", task = "run_clone_phylogeny", flag = "run_clone_phylogeny",
       cpu = "clone_phylogeny_cpu", memory = "clone_phylogeny_memory_gb",
       future = NA, queue = "clone_phylogeny_lsf_queue"),
  list(id = "de_go", task = "run_de_go", flag = "run_de_go",
       cpu = "de_go_cpu", memory = "de_go_memory_gb",
       future = "de_go_future_globals_gib", queue = "de_go_lsf_queue"),
  list(id = "rshiny", task = "run_rshiny", flag = "run_rshiny",
       cpu = "rshiny_cpu", memory = "rshiny_memory_gb",
       future = NA, queue = "rshiny_lsf_queue")
)

indent_block <- function(text, spaces = 2L) {
  pad <- strrep(" ", spaces)
  paste0(pad, gsub("\n", paste0("\n", pad), text, fixed = TRUE))
}

call_inputs <- function(mod, wait_on_ref = NULL) {
  lines <- c(
    "snap_root = snap_root,",
    "container_image = container_image,",
    "notify_email = notify_email,",
    sprintf("cpu = %s,", mod$cpu),
    sprintf("memory_gb = %s,", mod$memory)
  )
  if (!is.na(mod$future)) {
    lines <- c(lines, sprintf("future_globals_gib = %s,", mod$future))
  }
  lines <- c(lines, sprintf("lsf_queue = %s,", mod$queue))
  if (!is.null(wait_on_ref)) {
    lines <- c(lines, sprintf("wait_on = %s,", wait_on_ref))
  }
  paste(lines, collapse = "\n")
}

gen_chain <- function(modules, idx = 1L, path_suffix = "", wait_on_ref = NULL) {
  if (idx > length(modules)) return("")

  mod <- modules[[idx]]
  alias <- paste0(mod$id, path_suffix)
  next_wait_if_run <- paste0(alias, ".done_flag")

  call_block <- sprintf(
    "call snap.%s as %s {\n  input:\n%s\n}",
    mod$task, alias, indent_block(call_inputs(mod, wait_on_ref), 4L)
  )

  run_body <- paste0(
    call_block, "\n",
    gen_chain(modules, idx + 1L, paste0(path_suffix, "_y"), next_wait_if_run)
  )
  skip_body <- gen_chain(modules, idx + 1L, paste0(path_suffix, "_n"), wait_on_ref)

  sprintf(
    "if (%s) {\n%s\n} else {\n%s\n}",
    mod$flag,
    indent_block(run_body, 2L),
    indent_block(skip_body, 2L)
  )
}

workflow_header <- function() {
    c(
    "version 1.3",
    "",
    "import \"tasks.wdl\" as snap",
    "",
    "# AUTO-GENERATED by scripts/generate-snap-wdl.R — do not edit by hand.",
    "# Re-generate: Rscript scripts/generate-snap-wdl.R",
    "#",
    "# All modules are optional via workflow_profile / run_* inputs in YAML.",
    "# Each enabled module waits on the last completed upstream step (skipped",
    "# modules are bypassed in the dependency chain).",
    "",
    "workflow sc_rna_seq_snap_downstream {",
    "  meta {",
    "    description: \"Resource-aware orchestration of snap modules from upstream onwards\"",
    "    author: \"DNB Bioinformatics Core / KIDS26 Team 15\"",
    "  }",
    "",
    "  input {",
    "    String snap_root",
    "    String container_image",
    "    String notify_email = \"user.name@stjude.org\"",
    "",
    "    Boolean run_upstream = false",
    "    Boolean run_integrative = false",
    "    Boolean run_cluster = false",
    "    Boolean run_contamination_removal = false",
    "    Boolean run_cell_types = false",
    "    Boolean run_clone_phylogeny = false",
    "    Boolean run_de_go = false",
    "    Boolean run_rshiny = false",
    "",
    "    Int num_samples = 8",
    "    Int estimated_cells_per_sample = 50000",
    "",
    "    Int upstream_cpu = 16",
    "    Int upstream_memory_gb = 30",
    "    Int upstream_future_globals_gib = 200",
    "    String upstream_lsf_queue = \"standard\"",
    "",
    "    Int integrative_cpu = 10",
    "    Int integrative_memory_gb = 96",
    "    Int integrative_future_globals_gib = 200",
    "    String integrative_lsf_queue = \"standard\"",
    "",
    "    Int cluster_cpu = 4",
    "    Int cluster_memory_gb = 48",
    "    Int cluster_future_globals_gib = 400",
    "    String cluster_lsf_queue = \"standard\"",
    "",
    "    Int contamination_cpu = 8",
    "    Int contamination_memory_gb = 96",
    "    Int contamination_future_globals_gib = 400",
    "    String contamination_lsf_queue = \"standard\"",
    "",
    "    Int cell_types_cpu = 4",
    "    Int cell_types_memory_gb = 64",
    "    String cell_types_lsf_queue = \"standard\"",
    "",
    "    Int clone_phylogeny_cpu = 16",
    "    Int clone_phylogeny_memory_gb = 30",
    "    String clone_phylogeny_lsf_queue = \"standard\"",
    "",
    "    Int de_go_cpu = 4",
    "    Int de_go_memory_gb = 32",
    "    Int de_go_future_globals_gib = 200",
    "    String de_go_lsf_queue = \"standard\"",
    "",
    "    Int rshiny_cpu = 4",
    "    Int rshiny_memory_gb = 30",
    "    String rshiny_lsf_queue = \"standard\"",
    "  }",
    "",
    "  Int total_estimated_cells = num_samples * estimated_cells_per_sample",
    ""
  )
}

workflow_footer <- function() {
  c(
    "",
    "  output {",
    "    Int cohort_num_samples = num_samples",
    "    Int cohort_total_estimated_cells = total_estimated_cells",
    "  }",
    "}",
    ""
  )
}

main <- function() {
  args <- parse_args(commandArgs(trailingOnly = TRUE))
  body <- gen_chain(MODULES)
  wdl <- paste(c(workflow_header(), indent_block(body, 2L), workflow_footer()), collapse = "\n")
  dir.create(dirname(args$output), recursive = TRUE, showWarnings = FALSE)
  writeLines(wdl, args$output)
  cat("Wrote", normalizePath(args$output, mustWork = FALSE), "\n")
  cat("  Modules:", paste(vapply(MODULES, `[[`, "", "id"), collapse = ", "), "\n")
}

if (sys.nframe() == 0L) main()
